config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users
  resources :widgets
  get '/my_widgets', to: 'widgets#my_widgets'
  get '/revoke_user', to: 'users#revoke_user'

  root to: "widgets#index"
end

app/models/resources/factory.rb
class Resources::Factory
  DOMAIN = "https://showoff-rails-react-production.herokuapp.com/".freeze
  HEADERS = { "Content-Type" => "application/json" }
  VERSION = "api/v1".freeze

  CLIENT_ID = "277ef29692f9a70d511415dc60592daf4cf2c6f6552d3e1b769924b2f2e2e6fe".freeze
  CLIENT_SECRET = "d6106f26e8ff5b749a606a1fba557f44eb3dca8f48596847770beb9b643ea352".freeze

  def self.get(url:, headers:)
    begin
      result = RestClient.get(url, headers= headers)
      self.handle_response(result)
    rescue RestClient::Unauthorized, RestClient::Forbidden => err
      return err.response
    rescue RestClient::ImATeapot => err
      return err.response
    rescue KeyError => e
      raise_configuration_error(
        missing_env: "config error",
        error: e
      )
    end
  end

  def self.post(url:, payload:, headers:)
    begin
      result = RestClient.post(url, payload, headers= headers)
      self.handle_response(result)
    rescue RestClient::Unauthorized, RestClient::Forbidden => err
      return err.response
    rescue RestClient::ImATeapot => err
      return err.response
    rescue KeyError => e
      raise_configuration_error(
        missing_env: "config error",
        error: e
      )
    end
  end

  def self.path
    DOMAIN.dup + VERSION.dup
  end

  def self.input
    @payload.merge!({
      client_id: CLIENT_ID,
      client_secret: CLIENT_SECRET
    })
  end

  def self.raise_configuration_error(missing_env:, error:)
    recourse = "Please ensure the following ENV var(s) are set: #{Array(missing_env).join(" ")}"
    raise error
  end

  def self.handle_response(res)
    JSON.parse(res).dig("data")
  end

  def self.access_token
    User&.current_token
  end

  def self.token
    self.access_token&.dig("token_type") + ' ' + self.access_token&.dig("access_token") unless self.access_token.nil?
  end
end

app/models/resources/user_factory.rb
class Resources::UserFactory < Resources::Factory
  def self.post(url: nil, payload:, headers: nil)
    url = path + "/users" if url.nil?
    @payload = payload

    super(url: url, payload: input.to_json, headers: headers || HEADERS)
  end

  def self.revoke_user
    url = DOMAIN + "/oauth/revoke"
    headers= { "Authorization" => self.token }.merge!(HEADERS)

    self.post(url: url, payload: { token: self.access_token.dig("access_token") }, headers: headers)
  end
end

app/models/resources/widget_factory.rb
class Resources::WidgetFactory < Resources::Factory
  def self.get(term, me: false)
    url = self.path + "/widgets/visible?" + "client_id=" + CLIENT_ID + "&client_secret=" + CLIENT_SECRET
    url = self.path + "/widgets/visible?" + "client_id=" + CLIENT_ID + "&client_secret=" + CLIENT_SECRET + "&term=" + term if term.present?

    url = self.path + "/users/me/widgets?" + "client_id=" + CLIENT_ID + "&client_secret=" + CLIENT_SECRET unless me == false

    headers= {"Authorization" => self.token }.merge!(HEADERS)
    super(url: url, headers: headers)
  end

  def self.post(url: nil, payload:)
    url = path + "/widgets"
    headers= {"Authorization" => self.token }.merge!(HEADERS)
    super(url: url, payload: payload.to_json, headers: headers)
  end

  def self.me
    self.get(nil, me: true)
  end
end

app/models/user.rb
class User
  def self.create_user(params)
    @user ||= Resources::UserFactory.post(payload: { :user => params })
  end

  def self.current_user
    @user
  end

  def self.current_token
    self.current_user&.dig("token")
  end

  def self.revoke_user
    Resources::UserFactory.revoke_user if User.current_user.present?
    @user = nil
  end

  attr_accessor :first_name, :last_name, :email, :password, :image_url, :access_token, :payload, :token_type, :refresh_token, :email
end

app/models/widget.rb
class Widget
  def self.all(term)
    @user = Resources::WidgetFactory.get(term)
  end

  def self.me
    @user = Resources::WidgetFactory.me
  end

  def self.create_widget(params)
    @widget = Resources::WidgetFactory.post(payload: { :widget => params })
  end

  attr_accessor :name, :description, :kind
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def current_user
    User.current_user
  end

  helper_method :current_user
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.create_user(user_params)

    if @user.present?
      redirect_to widgets_path
    else
      render 'new'
    end
  end

  def new
    @user = User.new
  end

  def revoke_user
    User.revoke_user
    current_user = nil
    redirect_to root_path
  end

  def reset_password
    @user = User.reset(user_params)
  end

  private
  def user_params
    params.required(:user).permit(:first_name, :last_name, :email, :password, :image_url)
  end
end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
  def index
    @widgets = Widget.all(term)
    widgets
  end

  def create
    @widget = Widget.create_widget(widget_params)

    if @widget.present?
      redirect_to widgets_path
    else
      render 'new'
    end
  end

  def new
    @widget = Widget.new
  end

  def my_widgets
    @widgets = Widget.me
    widgets
    render 'index'
  end

  private
  def term
    params&.dig("search")&.dig("term")
  end

  def widgets
    @widgets = @widgets&.dig("widgets")
  end

  def widget_params
    params.require(:widget).permit(:name, :description, :kind)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/widgets_helper.rb
module WidgetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TechTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: '/shared/header' %>
    <%= yield %>
    <%= render 'users/new' %>
  </body>
</html>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark">
  <%= link_to "TechTest", root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "", "", class: 'navbar-brand' %>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <ul class="navbar-nav mr-auto">
        <% if current_user.nil? %>
          <li class="nav-item active">
            <%= link_to "SignUp", new_user_path, "data-toggle" => "modal", 'data-target' => '#signUp', class: 'btn btn-primary' %>
          </li>
        <% end %>
      </ul>
      <% if current_user.present? %>
        <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.dig("user").dig("name") %>
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <%= link_to "Logout", revoke_user_path, class: 'dropdown-item' %>
            <%= link_to "Reset Password", "", class: 'dropdown-item' %>
          </div>
        </div>
      <% end %>
    </form>
  </div>
</nav>

app/views/users/_new.html.erb
<%= simple_form_for :user, url: users_path do |f| %>
  <div class="modal fade show" id="signUp" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle">SignUp</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="container">
            <%= f.input :first_name, input_html: { required: true } %>
            <%= f.input :last_name, input_html: { required: true } %>
            <%= f.input :image_url %>
            <%= f.input :email, input_html: { required: true } %>
            <%= f.input :password, hint: 'No special characters.', input_html: { required: true } %>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= f.button :submit, class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/index.html.erb
testing

app/views/users/new.html.erb
<%= simple_form_for :user, url: users_path do |f| %>
  <div class="modal fade show" id="signUp" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle">SignUp</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="container">
            <%= f.input :first_name, input_html: { required: true } %>
            <%= f.input :last_name, input_html: { required: true } %>
            <%= f.input :image_url %>
            <%= f.input :email, input_html: { required: true } %>
            <%= f.input :password, hint: 'No special characters.', input_html: { required: true } %>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= f.button :submit, class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/new.js.erb
$("#signUp").html("<%= j (render 'new') %>");
$("#signUp").modal();

app/views/widgets/index.html.erb
<div class="container top">
  <div class="main">
    <div>
      <h3 class="title">Widgets</h3>
    </div>
    <div class="main">
      <%= link_to "All", widgets_path, class: "btn btn-primary" %>
      <% if current_user.present? %>
        <%= link_to "MyWidgets", my_widgets_path, class: "btn btn-primary" %>
        <%= link_to "Create", new_widget_path, class: "btn btn-primary" %>
      <% end %>
      <span style="width: 20px"></span>
      <%= simple_form_for :search, url: widgets_path, method: "GET", html: { class: 'form-inline' } do |f| %>
        <%= f.input :term, label: false, input_html: { required: false } %>
        <%= f.submit "Search", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
  <div class="row">
    <% @widgets.each do |widget| %>
    <div class="col-sm-6">
      <div class="card">
        <div class="card-header">
          <%= widget&.dig("name") %>
        </div>
        <div class="card-body">
          <p  class="card-text"> <%= widget&.dig("description") %> </p>
        </div>
        <div class="card-footer text-muted">
          User: <%= widget.dig("user")&.dig("name") %>
        </div>
      </div>
      <br/>
    </div>
    <% end %>
  </div>
</div>

app/views/widgets/new.html.erb
<%= simple_form_for :widget, url: widgets_path do |f| %>
  <div class="container top">
    <%= f.input :name, input_html: { required: true } %>
    <%= f.input :description, :as => :text, :input_html => { :rows => 7 , :style => 'width: 100%', required: true } %>
    <%= f.input :kind, :collection => %w[visible hidden] %>
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>